// File: app/(auth)/layout.tsx
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Smart School",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="min-h-screen w-full flex items-center justify-center bg-gray-50">
      {children}
    </div>
  );
}