"use client";
// File: app/layout.tsx
import type { Metadata } from "next";
// import { Cairo } from "next/font/google";
import "./globals.css";
import { MainProviders } from "./providers";
// import { Providers } from "./provider/providers";
// import { Providers } from "./providers";  // import { Providers } from "./providers";

// const cairo = Cairo({ subsets: ["arabic"] });

// export const metadata: Metadata = {
//   title: "Smart School",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html  >
      <body className={`Cairo`}>
        {/* {children} */}
        <MainProviders>{children}</MainProviders>
      </body>
    </html>
  );
}